on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -e .
        pytest tests
    - name: Cache python dependencies
      uses: actions/cache@v3
      env:
          cache-name: cache-pip-dependencies
      with:
        path: .venv
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('pyproject.toml') }}


